// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq6XtV9J6I-FT-_ViYI4PtcY7xa4v2H3c',
    appId: '1:302652562841:web:4a0927bd97602b49e3c708',
    messagingSenderId: '302652562841',
    projectId: 'founders-scout-4fd54',
    authDomain: 'founders-scout-4fd54.firebaseapp.com',
    storageBucket: 'founders-scout-4fd54.firebasestorage.app',
    measurementId: 'G-KEXE5RB8SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7zvDGBopj527nvFD0RkOT2tXeX-oAnCY',
    appId: '1:302652562841:android:ce82bf3ca57016f1e3c708',
    messagingSenderId: '302652562841',
    projectId: 'founders-scout-4fd54',
    storageBucket: 'founders-scout-4fd54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD2zvHB5fq_e-x4ZAKHKt1DaNLFUVqVQk',
    appId: '1:302652562841:ios:ab5c075ca88f33e4e3c708',
    messagingSenderId: '302652562841',
    projectId: 'founders-scout-4fd54',
    storageBucket: 'founders-scout-4fd54.firebasestorage.app',
    iosBundleId: 'com.foundersscout.foundersScout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD2zvHB5fq_e-x4ZAKHKt1DaNLFUVqVQk',
    appId: '1:302652562841:ios:ab5c075ca88f33e4e3c708',
    messagingSenderId: '302652562841',
    projectId: 'founders-scout-4fd54',
    storageBucket: 'founders-scout-4fd54.firebasestorage.app',
    iosBundleId: 'com.foundersscout.foundersScout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq6XtV9J6I-FT-_ViYI4PtcY7xa4v2H3c',
    appId: '1:302652562841:web:005f54a5c519da86e3c708',
    messagingSenderId: '302652562841',
    projectId: 'founders-scout-4fd54',
    authDomain: 'founders-scout-4fd54.firebaseapp.com',
    storageBucket: 'founders-scout-4fd54.firebasestorage.app',
    measurementId: 'G-2PSQH3GY8X',
  );
}
